# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.12

      - name: Install the project
        run: uv pip sync requirements.txt

      - name: Run tests
        run: uv run pytest
        env:
          SECRET_KEY: 21290asdkja
          DEBUG: True
          DATABASE_URL: sqlite:///test.db
          ENV: local
          ALLOWED_HOSTS: localhost
          SENDGRID_API_KEY: 123
          FROM_EMAIL: pybites@example.com
          ADMIN_USERS: pybites
          CELERY_BROKER_URL: amqp://guest:guest@localhost
